// categories.js
export const categories = [
    {
        name: "🧮 Mathematics",
        subcategories: [
        "Arithmetic",
        "Algebra",
        "Geometry",
        "Trigonometry",
        "Calculus",
        "Statistics & Probability",
        "Linear Algebra",
        "Discrete Mathematics",
        "Differential Equations",
        "Number Theory",
        "Applied Mathematics",
        "Mathematical Logic",
        ],
    },
    {
        name: "🔬 Natural Sciences",
        subcategories: [
        "Physics",
        "Chemistry",
        "Biology",
        "Astronomy",
        "Earth Science",
        "Environmental Science",
        "Geology",
        "Oceanography",
        "Meteorology",
        "Ecology",
        "Anatomy & Physiology",
        "Genetics",
        "Biochemistry",
        ],
    },
    {
        name: "🧠 Social Sciences",
        subcategories: [
        "Psychology",
        "Sociology",
        "Anthropology",
        "Political Science",
        "Economics",
        "Human Geography",
        "Criminology",
        "Archaeology",
        "Linguistics",
        "International Relations",
        ],
    },
    {
        name: "📚 Humanities",
        subcategories: [
        "History",
        "Philosophy",
        "Literature",
        "Religious Studies",
        "Cultural Studies",
        "Ethics",
        "Logic",
        "Classics",
        ],
    },
    {
        name: "💬 Languages & Communication",
        subcategories: [
        "English Language",
        "Creative Writing",
        "Journalism",
        "Media Studies",
        "Public Speaking",
        "Foreign Languages (Spanish, French, German, etc.)",
        "Linguistics",
        "Translation & Interpretation",
        ],
    },
    {
        name: "💻 Technology & Computer Science",
        subcategories: [
        "Computer Science",
        "Programming",
        "Information Technology",
        "Web Development",
        "Cybersecurity",
        "Artificial Intelligence",
        "Data Science",
        "Computer Networks",
        "Software Engineering",
        "Operating Systems",
        "Database Systems",
        ],
    },
    {
        name: "⚙️ Engineering",
        subcategories: [
        "Mechanical Engineering",
        "Electrical Engineering",
        "Civil Engineering",
        "Chemical Engineering",
        "Aerospace Engineering",
        "Biomedical Engineering",
        "Industrial Engineering",
        "Environmental Engineering",
        "Robotics",
        "Systems Engineering",
        ],
    },
    {
        name: "💼 Business & Economics",
        subcategories: [
        "Accounting",
        "Finance",
        "Business Administration",
        "Marketing",
        "Management",
        "Entrepreneurship",
        "Human Resources",
        "Supply Chain & Operations",
        "Economics (Micro & Macro)",
        "Business Law",
        ],
    },
    {
        name: "🧬 Health & Medicine",
        subcategories: [
        "Medicine",
        "Nursing",
        "Pharmacology",
        "Public Health",
        "Nutrition",
        "Anatomy",
        "Physiology",
        "Pathology",
        "Dentistry",
        "Veterinary Medicine",
        "Medical Ethics",
        ],
    },
    {
        name: "🎨 Arts & Design",
        subcategories: [
        "Visual Arts",
        "Music Theory",
        "Performing Arts",
        "Film Studies",
        "Graphic Design",
        "Architecture",
        "Photography",
        "Theater",
        "Dance",
        "Art History",
        "Fashion Design",
        ],
    },
    {
        name: "🧭 Education & Pedagogy",
        subcategories: [
        "Teaching Methods",
        "Curriculum Development",
        "Educational Psychology",
        "Special Education",
        "Classroom Management",
        "Early Childhood Education",
        ],
    },
    {
        name: "🌍 Global & Cultural Studies",
        subcategories: [
        "World History",
        "Global Studies",
        "Cultural Anthropology",
        "Area Studies (e.g., Latin American, Asian, African Studies)",
        "International Development",
        ],
    },
    {
        name: "🔧 Applied & Vocational Fields",
        subcategories: [
        "Agriculture",
        "Culinary Arts",
        "Automotive Technology",
        "Construction",
        "Hospitality & Tourism",
        "Law Enforcement",
        "Fire Science",
        "Aviation",
        ],
    },
];
